spring:
  application:
    name: admin-server
  config:
    import: optional:configserver:${SPRING_CLOUD_CONFIG_COMPONENT_URI:http://localhost:8888/}


---
spring:
  config:
    activate:
      on-profile: docker
    import: configserver:http://config-server:8888
